export const generatorNames = {
  "3Jhkp3Xtg2wyT6NoEtJB2VQPAHiYuqYUVBp": "Baza",
  "3Jfb7VJzmJjXyQDQ5Nw8R7G2MiasM5fm3Uy": "Binance",
  "3JqTwkbDFbtCPo9z5bFa9WfLmjEr7PXNode": "LTO Edge Node",
  "3JnZLvmVBXsc2XMug4e6yjyvPehr1Fjx9oM": "Lowsea Leasing",
  "3Jq3F3njrrR1ZvM3JhwLX2Sh56LQDtuEyu9": "Stakely.io",
  "3JffJmwV2G158V6N27ouzkoRTgEVPLFqxPy": "ThePhonenixNest",
  "3JsZN7TwprVdXr9CbQ9EUvLSBG2YSZgdPGB": "BlackTurtleNode",
  "3JnN8psLjuEyiPbH2bYcEFKUFpcamxzwFiv": "LTONode.com",
  "3JwUPNbGzguXqvZoAyPYsVDjqURMFVXp9WX": "StockholmBlockBuilders",
  "3JmcAJMQhdLKj296xoDkng9r1McCmBSFiEX": "ltoleasing",
  "3JkfhvV51FTDnCNpgZt3wjXNYbPehgFdaZA": "FillTheDoc",
  "3Jt1mBoziZmoGDaYe1UbGygGMsGS493vkgN": "Knight's Bay Leasing",
  "3Jq8mnhRquuXCiFUwTLZFVSzmQt3Fu6F7HQ": "LegalThings",
  "3Jg3DZyhBnNacHiY13624NQDsxBmnwnqNRQ": "LTO Blockchain Node",
  "3JtBYdoHJoQbgf8hYvEz1pyp7jj9URWvvbB": "CryptoBieb Lease",
  "3JqGGBMvkMtQQqNhGVD6knEzhncb55Y7JJ5": "KruptosNomisma-BiWeekly",
  "3JyXXG6zMKrVkeNdcg3cTRBLRJcbDZcf6RR": "zolnode",
  "3JnYB1TzHYS3gYDvczYtNUnmEbJsgmsdWY3": "LunarWhale Node",
  "3Jn6jpPBVmi1RLRpUtQGKVibNZpeTRACK2P": "KruptosNomisma-Monthly",
  "3JujV7o14LM3vo9bpXtZmqAkyBFwzVJJWdn": "Stats Support Node",
  "3Jp9rSY8BCk8DbfDRcqeULNrecWRRP7ShLr": "LTO MoonBase Node",
  "3JiNi1B3LVdF9Aa2P3cBA2NNwLP7XNaV9A5": "LTO.lease | Thor",
  "3JbXLTSZoU5os2JsTkMorhvvna6Z2dvhBUC": "Binnostake",
  "3Jv111Z8F2TMV2pWyFLJnBuoQaysUUiLEAS": "ltonod.es",
  "3JsyNRBHaU97DUVKMJKMARVHnJiGjAxMsCV": "LTO Stream Node",
  "3JgFnajhMZPidSzXQ1VrEmvfY2fARZ8FPsR": "zolnode2",
  "3JgZdq3LgP2qdB8cPFbuhdDV61u3qdqx2MP": "LTO Elites Leasing",
};
